version: '3'
services:
  nginx-rtmp:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"   # RTMP portu
      - "9090:8081"     # HTTP HLS portu
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/my-stream.conf:ro
      - ./html:/www/static/:ro   # index.html buradan gelecek

